#!/bin/python3

import math
import os
import random
import re
import sys
import string

#
# Complete the 'pangrams' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def pangrams(s):
    # Write your code here
    s = s.lower()
    dic = dict()
    count = 0
    for each in s:
        if str.lower(each) and each not in dic:
            dic[each] = 1
            count = count+1
    
    if count == 27:
        return 'pangram'
    return 'not pangram'
    

s = input()

result = pangrams(s)
print(result)
